
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(20)
driver.get("https://automationbysqatools.blogspot.com/2021/05/dummy-website.html")
driver.find_element(By.XPATH, "//input[@value='radio_345']").click()
driver.find_element(By.ID, "firstname").send_keys("Amit")
driver.find_element(By.ID, "firstname").send_keys("Mehra")  
driver.find_element(By.ID, "birthday").send_keys("25-07-2025")
driver.find_element(By.ID, "male").click()
driver.find_element(By.ID, "admorepass").click()
driver.find_element(By.XPATH, "//option[@value='1']").click()
driver.find_element(By.ID, "roundtrip").click()
driver.find_element(By.ID, "fromcity").send_keys("Chennai")
driver.find_element(By.ID, "destcity").send_keys("Mumbai")
driver.find_element(By.ID, "departdate").send_keys("25-07-2025")
driver.find_element(By.ID, "returndate").send_keys("31-07-2025")
driver.find_element(By.ID, "visadate").send_keys("6-08-2025")
driver.find_element(By.ID, "eamil").click()
driver.find_element(By.ID, "billing_name").send_keys("Vishal Mehra")
driver.find_element(By.ID, "billing_phone").send_keys("9887656793")
driver.find_element(By.ID, "billing_email").send_keys("mehra@gmail.com")
driver.find_element(By.ID, "billing_address").send_keys("Chennai")
driver.find_element(By.ID, "billing_country").click()
driver.find_element(By.XPATH, "//option[@vlaue='IN']").click()
driver.find_element(By.ID, "postcode").send_keys("60056")
driver.find_element(By.ID, "Prefecture").send_keys("Tamil nadu")
driver.find_element(By.ID, "street_address1").send_keys("Anantpur")
driver.find_element(By.ID, "street_address2").send_keys("mugappair")
driver.find_element(By.XPATH, "//input[@value='checkbox']").click()
time.sleep(5)
driver.close()